apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
  - name: test-git-clone-container
    image: ubuntu:latest  
    command: ["/bin/bash"]
    args: ["-c", "sleep 3600"]  # Keep the container running for you to exec into it
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Never
