version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.37.1
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    network_mode: "host"

  grafana:
    image: grafana/grafana:9.2.4
    container_name: grafana
    ports:
      - "3000:3000"
    network_mode: "host"
